config/routes.rb
Bookmarks::Application.routes.draw do
  resources :accounts

  resources :bookmarks
  resources :profiles, only: [:index, :show] do
    member do 
      get 'follow'
      get 'unfollow'
    end
  end

  devise_for :users

  get "about"  => "site#about", as: :about

  root 'site#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
	
  validates :name, length: { minimum: 8 }, presence: true
  validates :password, presence: true

  paginates_per 25
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :title, length: { minimum: 8 }, presence: true
  validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true

  paginates_per 25

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :bookmarks, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name:  "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false},
    format: {with: /\w+/}

  def to_param
    self.username
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id) ? true : false
  end

  def follow(other_user)
    relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    relationships.where(followed_id:  other_user.id).first.destroy
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /accounts
  def index
    @accounts = current_user.accounts.order('created_at desc').page(params[:page])
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.accounts.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = current_user.accounts.new(account_params)

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.accounts.where(id: params[:id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def account_params
      params.require(:account).permit(:name, :user_name, :email, :password, :description, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bookmarks
  def index
    @bookmarks = current_user.bookmarks.order('created_at desc').page(params[:page])
  end

  # GET /bookmarks/1
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = current_user.bookmarks.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark, notice: 'Bookmark was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /bookmarks/1
  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: 'Bookmark was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /bookmarks/1
  def destroy
    @bookmark.destroy
    redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      unless @bookmark = current_user.bookmarks.where(id: params[:id]).first
        flash[:alert] = 'Bookmark not found.'
        redirect_to root_url
      end
    end

    # Only allow a trusted parameter "white list" through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :follow, :unfollow]
  def index
    @users = User.page(params[:page])
  end

  def show
    if @user
      @bookmarks = @user.bookmarks.page(params[:page])
      @accounts = @user.accounts.page(params[:page])
      @followers =  @user.followers
      @followings = @user.followed_users
    else
      flash[:alert] = 'Profile not found.'
      redirect_to profiles_path
    end
  end

  def follow
    if current_user.follow(@user)
      flash[:notice] = "Follow successfully."
    else
      flash[:alert] = 'Action Failed.'
    end
    redirect_to :back  
  end

  def unfollow
    if current_user.unfollow(@user)
      flash[:notice] = "Unfollow successfully."
    else
      flash[:alert] = 'Action Failed.'
    end
    redirect_to :back  
  end

  private

    def set_user
      @user = User.where(username: params[:id]).first
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	
  def index
  	feed = Feedjira::Feed.fetch_and_parse("http://feeds.feedburner.com/TechCrunch/")
    @entry = feed.entries.last(10)
    @bookmarks = Bookmark.order('created_at desc').page(params[:page]) if current_user
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :user_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts of <%= current_user.username %></h1>

<table>
  <thead>
    <tr>
      <th>Account name</th>
      <th>Email</th>
      <th>User Name</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.email %></td>
        <td><%= account.user_name %></td>
        <td><%= account.password %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path, class: 'button' %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account name:</strong>
  <%= @account.name %>
</p>
<p>
  <strong>User name:</strong>
  <%= @account.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @account.password %>
</p>

<p>
  <strong>Description:</strong>
  <%= @account.description %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<h2>Your bookmarks</h2>

<table class="responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @bookmarks %>

<%= link_to 'New Bookmark', new_bookmark_path, class: 'button' %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @bookmark.user_id %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Bookmarks" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <!-- Navigation -->

        <div class="row">
          <div class="large-12 columns">

            <nav class="top-bar">
              <ul class="title-area">
                <!-- Title Area -->
                <li class="name">
                  <h1><a href="/">Kumar-devs Bookmarks</a></h1>
                </li>
              </ul>

              <section class="top-bar-section">
                <ul class="left">
                  <li class="divider"></li>
                  <li><%= link_to 'Users', profiles_path %></li>
                </ul>
                <!-- Right Nav Section -->
                <ul class="right">
                  <li class="divider"></li>
                  <% if current_user %>
                    <li><%= link_to 'My Bookmarks', bookmarks_path %></li>
                    <li class="divider"></li>

                    <li><%= link_to 'My Accounts', accounts_path %></li>
                    <li class="divider"></li>

                    <li class="has-dropdown">
                      <%= link_to current_user.username, '#'%>
                      <ul class="dropdown">
                        <li><%= link_to 'Profile', edit_user_registration_path %></li>
                        <li><%= link_to 'Logout', destroy_user_session_path %></li>
                        <li class="divider"></li>
                      </ul>
                    </li>
                  <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                    <li><%= link_to 'Register', new_user_registration_path %></li>
                  <% end %>
                </ul>
              </section>
            </nav>
            <!-- End Top Bar -->
          </div>
        </div>
        <!-- End Navigation -->

        <!-- Flash messages -->
        <div class="row">
          <div class="large-12 columns">
            <% if flash[:notice] %>
              <div data-alert class="alert-box success">
                <a href="#" class="close">&times;</a>
                <%= flash[:notice] %>
              </div>
            <% end %>

            <% if flash[:alert] %>
              <div data-alert class="alert-box alert">
                <a href="#" class="close">&times;</a>
                <%= flash[:alert] %>
              </div>
            <% end %>
          </div>
        </div>
        <!-- End Flash messages -->

        <!-- Content -->
        <div class="row">
          <div class="large-12 columns">
            <%= yield %>
          </div>
        </div>
        <!-- End Content -->

        <!-- Footer -->
        <footer class="row">
          <div class="large-12 columns"><hr />
            <div class="row">
              <div class="large-6 columns">
                <p>&copy; Copyright to Kumar-devs.</p>
              </div>

              <div class="large-6 columns">
                <ul class="inline-list right">
                  <li><%= link_to("About", about_path) %></li>
                  <li><%= link_to("Twitter", "http://twitter.com/SuneelCS", :target => "_blank") %></li>
                  <li><%= link_to("Facebook", "http://facebook.com/skramchandani", :target => "_blank") %></li>
                  <li><%= link_to("LinkedIn", "http://www.linkedin.com/profile/view?id=136971021", :target => "_blank") %></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
        <!-- End Footer -->

      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/profiles/index.html.erb
<h2>Users that joined</h2>

<table class="responsive">
  <thead>
    <tr>
      <th>User</th>
      <th>#Followers </th>
      <th>#Following </th>
      <th># Bookmarks</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, profile_path(user) %></td>
        <td> <%= user.followers.count %> </td>
        <td> <%= user.followed_users.count %> </td>
        <td><%= user.bookmarks.count %></td>
        <td>
         <% unless current_user.eql?(user) %>
            <% if current_user.following?(user) %>
              <%= link_to "Unfollow", unfollow_profile_path(user) %>
            <% else %>
              <%= link_to "Follow", follow_profile_path(user) %>
            <% end %>  
         <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/profiles/show.html.erb
<h2>Bookmarks</h2>
<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
  <% @bookmarks.each do |bookmark| %>
    <tr>
    <td><%= link_to bookmark.title, bookmark.url, :target => "_blank" %></td>
    <td><%= link_to @user.username, profile_path(@user) %></td>
  </tr>
<% end %>
  </tbody>
</table>

<%= paginate @bookmarks %>
<% if current_user.eql?(@user) %>
  <h2>Accounts</h2>
  <table>
    <thead>
      <tr>
        <th>Account name</th>
        <th>Email</th>
        <th>User Name</th>
        <th>Password</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.name %></td>
          <td><%= account.email %></td>
          <td><%= account.user_name %></td>
          <td><%= account.password %></td>
          <td><%= link_to 'Show', account %></td>
          <td><%= link_to 'Edit', edit_account_path(account) %></td>
          <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= paginate @accounts %>
<% end %>


<h2 class="left">Followers </h2>
<% unless current_user.eql?(@user) %>
  <div class="right">  
    <% if current_user.following?(@user) %>
      <%= link_to("Unfollow", unfollow_profile_path(@user), class: "button") %>
    <% else %>  
      <%= link_to("Follow", follow_profile_path(@user), class: "button") %>
    <% end %>
  </div>
<% end %>  
<table>
  <thead>
    <tr>
      <th>User Name </th>
    </tr>
  </thead>
  <tbody>
    <% @followers.each do |user| %>
      <tr>
        <td><%= link_to user.username, profile_path(user) %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

<h2>Following </h2>
<table>
  <thead>
    <tr>
      <th>User Name </th>
    </tr>
  </thead>
  <tbody>
    <% @followings.each do |user| %>
      <tr>
        <td><%= link_to user.username, profile_path(user) %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

<%= link_to 'Back', profiles_path %>

app/views/site/about.html.erb
<div class="row">      
	<div class="large-12 columns">
		<h3>About this app</h3>
    <p>
    	This is a tutorial app developed by <a href="javascript:;" target="_blank">Suneel Kumar</a>. For the source code email <%= mail_to "sunny.ciitlahore@gmail.com", "sunny.ciitlahore@gmail.com" %>
    </p>
  </div>
</div>

app/views/site/index.html.erb
<div class="large-8 columns">
  <% if current_user %>
    <h2>Latest Bookmarks</h2>
    <table class="responsive">
      <thead>
        <tr>
          <th>Url</th>
          <th>User</th>
        </tr>
      </thead>

      <tbody>
        <% @bookmarks.each do |bookmark| %>
          <tr>
            <td><%= link_to bookmark.title, bookmark.url, :target => "_blank" %></td>
            <td><%= link_to bookmark.user.username, profile_path(bookmark.user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @bookmarks %>
  <% else %>
    <div class="panel">
      <h1>Share your bookmarks and Save your personal accounts information. </h1>
      <p>A simple app to track and share your beloved bookmarks with others.</p>
      <%= link_to "Get started today", new_user_registration_path, :class => "button button-large" %>
    </div>

    <hr>
  <% end %> 
</div>
<div class="large-4 columns">
  <h2>Latest News</h2>
  <ul>
  <% @entry.each do |feed|%>
    <li style="list-style:none;"><%= link_to "#{feed.title.sanitize}", "#{feed.url}",:target => "_blank" %></li>
  <%end%>
  </ul>
</div>  